language: objective-c
osx_image: xcode12.0
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project "DuoAPISwift.xcodeproj" -scheme "DuoAPISwift" -sdk "macosx10.14" build test | xcpretty
  - pod lib lint
