language: objective-c
osx_image: xcode8
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=DuoAPISwift.xcworkspace
  - MACOS_SDK=macosx10.12
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild clean build test -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$MACOS_SDK" | xcpretty
  - pod lib lint
